AlwasataNew/Controllers/ReportController.cs
using AlwasataNew.Data;
using AlwasataNew.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Security.Claims;
using static System.Net.Mime.MediaTypeNames;

namespace AlwasataNew.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ReportController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CustomerReports()
        {
            var customers=_context.Customers.AsNoTracking().ToList();
            return View(customers);            
        }

        public IActionResult CampaignsCustomers(DateTime? date)
        {
            var customers=new List<Customer>();
            if (date!=null)
            {
                var newDate = Convert.ToDateTime(date);
                var list = _context.Customers.Where(x => x.CustomerComeFrom == "Internet" || x.CustomerComeFrom == "حملات التسويق").AsNoTracking().ToList();
                list = list.OrderByDescending(x => Convert.ToDateTime(x.CreatedAt)).ToList();
                foreach (var item in list)
                {
                    if(Convert.ToDateTime(item.CreatedAt).Month==newDate.Month)
                    {
                        customers.Add(item);
                    }
                }

            }
            else
            {
                customers = _context.Customers.Where(x => x.CustomerComeFrom == "Internet" || x.CustomerComeFrom == "حملات التسويق").AsNoTracking().ToList();
                customers = customers.OrderByDescending(x => Convert.ToDateTime(x.CreatedAt)).ToList();
            }
            return View(customers);
        }

        public IActionResult OtherSourcesCustomers(string? customerType)
        {
            var customers=new List<Customer>();
            if (customerType!=null)
            {
                if(customerType=="متابعين")
                {
                    customers = _context.Customers.Where(x => x.CustomerComeFrom != "Internet" && x.CustomerComeFrom != "حملات التسويق" && x.FollowBy!=null).AsNoTracking().ToList();
                    customers=customers.OrderByDescending(x=>Convert.ToDateTime(x.CreatedAt)).ToList();
                }
                else
                {
                    customers = _context.Customers.Where(x => x.CustomerComeFrom != "Internet" && x.CustomerComeFrom != "حملات التسويق" && x.FollowBy==null).AsNoTracking().ToList();
                    customers = customers.OrderByDescending(x => Convert.ToDateTime(x.CreatedAt)).ToList();

                }

                return View(customers);

            }
            else
            {
                 customers = _context.Customers.Where(x => x.CustomerComeFrom != "Internet" && x.CustomerComeFrom != "حملات التسويق").AsNoTracking().ToList();
                customers = customers.OrderByDescending(x => Convert.ToDateTime(x.CreatedAt)).ToList();

            }
            return View(customers);
        }

        public IActionResult EmployeeReports()
        {
            using var dbContext = new ApplicationDbContext();
            var employee = dbContext.Users.ToList();
            return View(employee);
        }

        public IActionResult SalesReports()
        {
            return View();
        }


        public List<Customer> GetAllCustomer()
        {
            using (var dbContext = new ApplicationDbContext())
            {
                if (User.IsInRole("Admin"))
                {
                    var allCustomer = dbContext.Customers.OrderBy(x => x.CreatedAt).AsNoTracking().ToList();
                    return allCustomer;
                }
                else
                {

                    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                    var resultt = dbContext.Users.Where(x => x.Id == userId).Select(x => new { FName = x.FirstName, LName = x.LastName }).FirstOrDefault();

                    string EmployeeName = resultt.FName + " " + resultt.LName;

                    var allCustomer = dbContext.Customers.Where(x => x.FollowBy == EmployeeName).OrderBy(x => x.CreatedAt).AsNoTracking().ToList();

                    return allCustomer;

                }

            }
        }

        public JsonResult GetAllCustomerWithKeyWord(string text)
        {
            var configuration = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
            string constr = configuration.GetConnectionString("DefaultConnection");
            SqlConnection con = new SqlConnection(constr);
            if (User.IsInRole("Admin"))
            {
                string s1 = $"select * from Customers where CustomerName like '%{text}%' or Phone like '%{text}%' or CompanyName like '%{text}%' or Email like '%{text}%'";
                SqlCommand cmd = new SqlCommand(s1, con);
                SqlDataAdapter da = new SqlDataAdapter(cmd);

                DataSet ds = new DataSet();
                da.Fill(ds);

                List<Customer> ListCustomer = new List<Customer>();
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    ListCustomer.Add(new Customer
                    {
                        Id = Convert.ToInt32(dr["Id"]),
                        CustomerName = dr["CustomerName"].ToString(),
                        CompanyName = dr["CompanyName"].ToString(),
                        CompanySite = dr["CompanySite"].ToString(),
                        CreatedAt = Convert.ToString(dr["CreatedAt"]),
                        CustomerState = dr["CustomerState"].ToString(),
                        Address = dr["Address"].ToString(),
                        Email = dr["Email"].ToString(),
                        FollowBy = dr["FollowBy"].ToString(),
                        EmployeeName = dr["EmployeeName"].ToString(),
                        JobTitle = dr["JobTitle"].ToString(),
                        Phone = Convert.ToString(dr["Phone"]),
                        Type = dr["Type"].ToString(),
                        CreatedBy = dr["CreatedBy"].ToString()
                    });
                }

                return Json(ListCustomer);
            }
            else
            {
                using var dbContext = new ApplicationDbContext();
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                var result = dbContext.Users.Where(x => x.Id == userId).Select(x => new { FName = x.FirstName, LName = x.LastName }).FirstOrDefault();

                string EmployeeName = result.FName + " " + result.LName;


                string s1 = $"select * from Customers where (CustomerName like '%{text}%' or Phone like '%{text}%' or CompanyName like '%{text}%' or Email like '%{text}%') and FollowBy ='{EmployeeName}'";
                SqlCommand cmd = new SqlCommand(s1, con);
                SqlDataAdapter da = new SqlDataAdapter(cmd);

                DataSet ds = new DataSet();
                da.Fill(ds);

                List<Customer> ListCustomer = new List<Customer>();
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    ListCustomer.Add(new Customer
                    {
                        Id = Convert.ToInt32(dr["Id"]),
                        CustomerName = dr["CustomerName"].ToString(),
                        CompanyName = dr["CompanyName"].ToString(),
                        CompanySite = dr["CompanySite"].ToString(),
                        CreatedAt = Convert.ToString(dr["CreatedAt"]),
                        CustomerState = dr["CustomerState"].ToString(),
                        Address = dr["Address"].ToString(),
                        Email = dr["Email"].ToString(),
                        FollowBy = dr["FollowBy"].ToString(),
                        EmployeeName = dr["EmployeeName"].ToString(),
                        JobTitle = dr["JobTitle"].ToString(),
                        Phone = Convert.ToString(dr["Phone"]),
                        Type = dr["Type"].ToString(),
                        CreatedBy = dr["CreatedBy"].ToString()
                    });
                }

                return Json(ListCustomer);

            }
        }

        public JsonResult GetAllCustomersLastMonth()
        {

            var configuration = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
            string constr = configuration.GetConnectionString("DefaultConnection");
            SqlConnection con = new SqlConnection(constr);
            int month = DateTime.Now.Month;
            string s1 = $"select * from Customers where MONTH(CreatedAt) = ${month}";
            SqlCommand cmd = new SqlCommand(s1, con);
            SqlDataAdapter da = new SqlDataAdapter(cmd);
            DataSet ds = new DataSet();
            da.Fill(ds);

            List<Customer> ListCustomer = new List<Customer>();
            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                ListCustomer.Add(new Customer
                {
                    Id = Convert.ToInt32(dr["Id"]),
                    CustomerName = dr["CustomerName"].ToString(),
                    CompanyName = dr["CompanyName"].ToString(),
                    CompanySite = dr["CompanySite"].ToString(),
                    CreatedAt = Convert.ToString(dr["CreatedAt"]),
                    CustomerState = dr["CustomerState"].ToString(),
                    Address = dr["Address"].ToString(),
                    Email = dr["Email"].ToString(),
                    FollowBy = dr["FollowBy"].ToString(),
                    EmployeeName = dr["EmployeeName"].ToString(),
                    JobTitle = dr["JobTitle"].ToString(),

AlwasataNew/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using System.Net.Mail;
using AlwasataNew.Models;
using AlwasataNew.ViewModel;
using System.ComponentModel.DataAnnotations;

namespace AlwasataNew.Controllers
{
    [Authorize(Roles ="Admin")]
    public class UsersController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(UserManager<ApplicationUser> userManager,RoleManager<IdentityRole> roleManager)
        {
            _userManager=userManager;
            _roleManager=roleManager;
        }


        public IActionResult Index()
        {
            var users =  _userManager.Users.Select(user => new UserViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                UserName = user.UserName,
                Email = user.Email,
                RolesName = _userManager.GetRolesAsync(user).Result
            }).ToList();

            users = users.Where(x=>x.RolesName.FirstOrDefault() != "Customer").ToList();
            return View(users);
        }

        public async Task<IActionResult> ManageRoles(string userId)
        {
            var user=await _userManager.FindByIdAsync(userId);

            if (user == null)
                NotFound();

            var roles = await _roleManager.Roles.ToListAsync();

            var viewModel = new UserRoleViewModel
            {
                userId = user.Id,
                userName = user.UserName,
                Roles = roles.Select(role => new RoleViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name,
                    IsSelected=_userManager.IsInRoleAsync(user,role.Name).Result
                }).ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageRoles(UserRoleViewModel model)
        {
            var user = await _userManager.FindByIdAsync(model.userId);

            if (user == null)
                NotFound();

            var userRoles = await _userManager.GetRolesAsync(user);

            foreach(var role in model.Roles)
            {
                if(userRoles.Any(r => r == role.RoleName) && !role.IsSelected)
                {
                    await _userManager.RemoveFromRoleAsync(user, role.RoleName);
                }

                if (!userRoles.Any(r => r == role.RoleName) && role.IsSelected)
                {
                    await _userManager.AddToRoleAsync(user, role.RoleName);
                }
            }

            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public async Task<IActionResult> AddNewUser()
        {
            var roles = await _roleManager.Roles.Select(r => new RoleViewModel { RoleId = r.Id, RoleName = r.Name }).ToListAsync();

            var ViewModel = new AddUserViewModel
            {
                Roles = roles
            };

            return View(ViewModel);
        }


        [HttpPost]
        public async Task<IActionResult> AddNewUser(AddUserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if(!model.Roles.Any(r => r.IsSelected))
            {
                ModelState.AddModelError("Roles", "Please Select At Least One Role");
                return View(model);
            }

            if(await _userManager.FindByEmailAsync(model.Email) != null)
            {
                ModelState.AddModelError("Email", "Email is Aleady Exist !");
                return View(model);
            }
            var username = "";
            if (model.Email != null && model.Password != null)
            {
                username = new EmailAddressAttribute().IsValid(model.Email) ? new MailAddress(model.Email).User : model.Email;
            }

            if (await _userManager.FindByNameAsync(username) != null)
            {
                ModelState.AddModelError("UserName", "User Name is Aleady Exist !");
                return View(model);
            }

            
            var user = new ApplicationUser
            {
                Email = model.Email,
                UserName = username,
                FirstName = model.FirstName,
                LastName = model.LastName,
                EmailConfirmed=true
            };

            var result = await _userManager.CreateAsync(user, model.Password);

            if (!result.Succeeded)
            {
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("Roles", error.Description);
                }
                return View(model);
            }

            await _userManager.AddToRolesAsync(user, model.Roles.Where(r => r.IsSelected).Select(r => r.RoleName));

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> EditProfile(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
                NotFound();


            var viewModel = new ProfileFormViewModel
            {
                Id=userId,
                FirstName=user.FirstName,
                LastName=user.LastName,
                Email=user.Email,
                UserName=user.UserName

            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProfile(ProfileFormViewModel model)
        {
            if(!ModelState.IsValid)
                return View(model);

            var user = await _userManager.FindByIdAsync(model.Id);

            if (user == null)
                NotFound();


            var userWithSameEmail = await _userManager.FindByEmailAsync(model.Email);

            if (userWithSameEmail != null && userWithSameEmail.Id!=model.Id)
            {
                ModelState.AddModelError("Email", "this Email is already assigned to another user !");
                return View(model);
            }



            var userWithSameUserName = await _userManager.FindByNameAsync(model.UserName);

            if (userWithSameUserName != null && userWithSameUserName.Id != model.Id)
            {
                ModelState.AddModelError("UserName", "this Username is already assigned to another user !");
                return View(model);
            }

            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.UserName = model.UserName;
            user.Email = model.Email;

            await _userManager.UpdateAsync(user);

            return RedirectToAction(nameof(Index));
        }

    }
}

AlwasataNew/Views/Home/Card.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container-fluid">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <h5 class="card-title fw-semibold mb-4">Card</h5>
                        <div class="card">
                            <img src="../assets/images/products/s4.jpg" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">Card title</h5>
                                <p class="card-text">
                                    Some quick example text to build on the card title and make up the bulk of
                                    the
                                    card's content.
                                </p>
                                <a href="#" class="btn btn-primary">Go somewhere</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <h5 class="card-title fw-semibold mb-4">Header and footer</h5>
                        <div class="card">
                            <div class="card-header">
                                Featured
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">Special title treatment</h5>
                                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                <a href="#" class="btn btn-primary">Go somewhere</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <h5 class="card-title fw-semibold mb-4">Titles, text, and links</h5>
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Card title</h5>
                                <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                                <p class="card-text">
                                    Some quick example text to build on the card title and make up the bulk of
                                    the
                                    card's content.
                                </p>
                                <a href="#" class="card-link">Card link</a>
                                <a href="#" class="card-link">Another link</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AlwasataNew/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@using AlwasataNew.Data;
@model List<string>
<link rel="stylesheet" href="~/css/site.css" />
<style>
    a {
        color: black;
        font-weight: bold;
    }

    .iconA {
        color: #615dff;
    }

    .AllCustomers {
        display: flex;
        justify-content: space-around;
        align-items: center;
    }

    .Customers {
        display: flex;  
        justify-content: center;    
        align-items: center;    
        width: 180px;       
        height: 180px;      
        border-radius: 50%;     
        flex-direction: column;     
        gap: 10px;      
        padding: 3px;       
    }
</style>


@{
    ApplicationDbContext dbContext = new ApplicationDbContext();
    var HamalatCount = dbContext.Customers.Where(x => x.CustomerComeFrom == "Internet" || x.CustomerComeFrom == "حملات التسويق").Count();
    var OtherCount = dbContext.Customers.Where(x => x.CustomerComeFrom != "Internet" && x.CustomerComeFrom != "حملات التسويق").Count();
}


<div class="spiner"></div>
<div class="container-fluid" style="display:none">
    <!--  Row 1 -->
    <div class="row" style="display:flex;justify-content:center">

        @if (User.IsInRole("Admin"))
        {
            <div class="allInformation col-md-12">
                <span class="all">
                    جميع الموظفين : <span>@((dbContext.Users.Count()) - 1)</span>
                </span>
                <span class="all">
                    جميع المشاريع : <span>@dbContext.Projects.Count()</span>
                </span>
                <span class="all">
                    جميع العملاء : <span>@dbContext.Customers.Count()</span>
                </span>
            </div>
            <div class="col-md-12 AllCustomers">
                <a asp-controller="Report" asp-action="OtherSourcesCustomers">
                    <div class="Customers" style="background-color: #b6ecb659;color: #040;">
                        <div style="border:1px solid;border-radius:50%;display:flex;justify-content:center;align-items:center;width:170px;height:170px;flex-direction:column;gap:10px;">
                            <span style="font-weight:bold">@OtherCount</span>
                            عملاء من مصادر اخرى
                            <i class="fa-solid fa-mug-hot fa-2x"></i>
                        </div>
                    </div>
                </a>
                <a asp-controller="Report" asp-action="CampaignsCustomers">
                    <div class="Customers" style="background-color: #6fb3c85e;color: #9d0000;">
                        <div style="border:1px solid;border-radius:50%;display:flex;justify-content:center;align-items:center;width:170px;height:170px;flex-direction:column;gap:10px;">
                            <span style="font-weight:bold">@HamalatCount</span>
                            عملاء من الحملات
                            <i class="fa-solid fa-fire fa-2x"></i>
                        </div>
                    </div>
                </a>
            </div>
            <h2 style="text-align:center;margin:30px auto;">جميع الموظفين</h2>
        }
        @foreach (var item in Model)
        {
            var user = dbContext.Users.Where(x => x.Id == item).FirstOrDefault();
            <div class="col-md-6">
                <div class="EmpDivInformation" dir="rtl">
                    <div class="empImg">
                        @if (user.ProfilePicture != null)
                        {
                            <img class="rounded-circle avatar" alt="ProfilePicture" src="data:image/*;base64,@(Convert.ToBase64String(user.ProfilePicture))" />
                        }
                        else
                        {
                            <img class="rounded-circle avatar" alt="ProfilePicture" src="~/assets/images/defaultPictureForProfile.jpg" />
                        }
                    </div>
                    <span style="margin:15px auto;display:block;font-size:18px;font-weight:bold">@user.FirstName @user.LastName</span>
                    <span class="empRole">
                        @{
                            var result = @dbContext.Roles.Where(x => x.Id == dbContext.UserRoles.Where(x => x.UserId == user.Id).Select(x => x.RoleId).FirstOrDefault()).Select(x => x.Name).FirstOrDefault();
                            if (result == "Marketer")
                            {
                                <span>مسوّق</span>
                            }
                            else if (result == "DirectorOfMarketing")
                            {
                                <span>مدير تسويق</span>
                            }
                        }
                    </span>
                    <div class="customerInfo">
                        <div style="margin:15px;font-size:18px">
                            @{
                                string empId = user.Id;
                            }
                            عدد العملاء : @dbContext.Customers.Where(x => x.FollowBy == empId).Count()
                            <i class="fa-solid fa-users fa-2x" style="margin-right:5px;color:#688bef"></i>
                            <div class="custState">
                                <div class="row" style="display:flex;justify-content:center">


                                    <div class="divState col-md-3">
                                        <span>جديد</span>
                                        <i class="fa-solid fa-square-arrow-up-right" style="color:darkgoldenrod"></i>
                                        <a asp-action="ShowListOfCustomerByState" asp-controller="Customer" asp-route-state="جديد" asp-route-empId="@empId">
                                            <div class="StateCount">@dbContext.Customers.Where(x => x.FollowBy == empId && (x.CustomerState == "جديد" || x.CustomerState == "رد" || x.CustomerState == "لم يرد" || x.CustomerState == "متفاعل" || x.CustomerState == "غير متفاعل" || x.CustomerState == "تم ارسال البيانات")).Count()</div>
                                        </a>

                                    </div>


                                    <div class="divState col-md-3">
                                        <span>متابعة</span>
                                        <i class="fa-solid fa-timeline" style="color:#1c52bb"></i>
                                        <a asp-action="ShowListOfCustomerByState" asp-controller="Customer" asp-route-state="متابعة" asp-route-empId="@empId">
                                            <div class="StateCount">@dbContext.Customers.Where(x => x.FollowBy == empId && x.CustomerState == "متابعة").Count()</div>
                                        </a>

                                    </div>


                                    <div class="divState col-md-3">
                                        <span>تعميد</span>
                                        <i class="fa-regular fa-circle-check" style="color:green"></i>
                                        <a asp-action="ShowListOfCustomerByState" asp-controller="Customer" asp-route-state="تعميد" asp-route-empId="@empId">
                                            <div class="StateCount">@dbContext.Customers.Where(x => x.FollowBy == empId && x.CustomerState == "تعميد").Count()</div>
                                        </a>
                                    </div>
                                    
                                    
                                    
                                </div>
                            </div>
                        </div>

                        @if (User.IsInRole("Admin"))
                        {
                            <div class="ManageUser">
                                <a asp-controller="Users" asp-action="Index" class="iconA">
                                    <i class="fa-solid fa-gear fa-2x"></i>
                                </a>
                            </div>
                        }

                        else
                        {
                            <div class="ManageUser">
                                <a asp-controller="Customer" asp-action="ManageCustomer" class="iconA">
                                    <i class="fa-solid fa-gear fa-2x"></i>
                                </a>
                            </div>
                        }
                    </div>
                </div>
            </div>

        }

    </div>

</div>
<script src="~/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $(() => {
        $(".spiner").fadeOut(500);
        $(".container-fluid").fadeIn(500);
    });
</script>